"""change column name looking to seeking

Revision ID: eca2857ec537
Revises: 0519e3fb37be
Create Date: 2022-08-12 18:09:08.152442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca2857ec537'
down_revision = '0519e3fb37be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('seeking_venue', sa.Boolean(), nullable=True))
    op.drop_column('artists', 'looking_for_venues')
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.drop_column('venues', 'looking_for_talents')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('looking_for_talents', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('venues', 'seeking_talent')
    op.add_column('artists', sa.Column('looking_for_venues', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('artists', 'seeking_venue')
    # ### end Alembic commands ###
